apiVersion: v1
kind: Secret
metadata:
  name: console
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  postgres.host: {{ .Values.secrets.postgres.host }}
  postgres.port: {{ .Values.secrets.postgres.port }}
  postgres.database: {{ .Values.secrets.postgres.database }}
  postgres.admin.username: {{ .Values.secrets.postgres.admin.username }}
  postgres.admin.password: {{ .Values.secrets.postgres.admin.password }}
  postgres.sandboxR.username: {{ .Values.secrets.postgres.sandboxR.username }}
  postgres.sandboxR.password: {{ .Values.secrets.postgres.sandboxR.password }}
  postgres.sandboxRW.username: {{ .Values.secrets.postgres.sandboxRW.username }}
  postgres.sandboxRW.password: {{ .Values.secrets.postgres.sandboxRW.password }}
  postgres.externalTaskSandbox.username: {{ .Values.secrets.postgres.externalTaskSandbox.username }}
  postgres.externalTaskSandbox.password: {{ .Values.secrets.postgres.externalTaskSandbox.password }}
  gcp.key: {{ .Values.secrets.gcp.key }}
  aws.key: {{ .Values.secrets.aws.key }}
  aws.secret: {{ .Values.secrets.aws.secret }}
  pbkdf2.iterations: {{ .Values.secrets.pbkdf2.iterations }}
  pbkdf2.keyLength: {{ .Values.secrets.pbkdf2.keyLength }}
  pbkdf2.saltLength: {{ .Values.secrets.pbkdf2.saltLength }}
  pbkdf2.digest: {{ .Values.secrets.pbkdf2.digest }}
  mailgun.apiKey: {{ .Values.secrets.mailgun.apiKey }}
  mailgun.domain: {{ .Values.secrets.mailgun.domain }}
  elasticsearch.url: {{ .Values.secrets.elasticsearch.url }}
  jwt.privateKey: {{ .Values.secrets.jwt.privateKey }}
  jwt.publicKey: {{ .Values.secrets.jwt.publicKey }}
  jwt.algorithm: {{ .Values.secrets.jwt.algorithm }}
  jwt.issuer: {{ .Values.secrets.jwt.issuer }}
  jwt.tokenExpiration: {{ .Values.secrets.jwt.tokenExpiration }}
  raven.dsn: {{ .Values.secrets.raven.dsn }}
