apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: 80
    protocol: TCP
  selector:
    app: console
