apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: openvpn
    port: {{ .Values.service.externalPort }}
    protocol: TCP
  selector:
    app: openvpn
