apiVersion: v1
kind: Service
metadata:
  name: yourls-mariadb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
  - name: mariadb
    port: {{ .Values.mariadb.service.externalPort }}
    targetPort: 3306
    protocol: TCP
  selector:
    app: yourls
    role: mariadb
