apiVersion: v1
kind: Secret
metadata:
  name: yourls
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  cookie: {{ .Values.web.secrets.cookie }}
  users: {{ .Values.web.secrets.users }}
