apiVersion: v1
kind: Service
metadata:
  name: yourls
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - name: http
    port: {{ .Values.web.service.externalPort }}
    targetPort: 80
    protocol: TCP
  selector:
    app: yourls
    role: web
