apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: circleci
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
