apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: wordpress-mariadb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  serviceName: wordpress-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        role: mariadb
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: comehome
        - name: MYSQL_DATABASE
          value: mariadb
        resources: {{ toJson .Values.mariadb.resources }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          readOnly: false
        readinessProbe:
          tcpSocket:
            port: 3306
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - {{ .Values.volumes.mariadb.accessMode }}
      resources:
        requests:
          storage: {{ .Values.volumes.mariadb.capacity }}
