apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: generic
data:
  credentials.json: {{ .Values.global.cloudsql.secrets.gcpServiceAccount }}
